name: examen_h3_todo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  auto_route: ^8.2.0
  appflowy_board: ^0.1.2
  logger: ^2.3.0
  gap: ^3.0.1
  url_strategy: ^0.2.0
  openapi_generator_annotations: ^4.11.0
  build_runner: ^2.4.6
  chopper: ^7.0.6
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  chopper_generator: ^7.0.4
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^2.11.10

flutter:
  uses-material-design: true

  assets:
    - assets/  
